### ISSUE TITLE
GRASS 8 changed behaviour, causes error in modelmanager.plugins.grass

### ISSUE THREAD

**Issue by tpilz** [mwort/modelmanager#5]
GRASS module  `script.setup` function `init()` changed API in version 8 (see [docs](https://grass.osgeo.org/grass80/manuals/libpython/script.html#module-script.setup), and [docs version 7.8](https://grass.osgeo.org/grass78/manuals/libpython/script.html#module-script.setup)). This causes an error in modelmanager's the grass plugin resulting from [grass.py#L116](https://github.com/mwort/modelmanager/blob/ded334410f3d68723d3f2cae0a5174cd25f62187/modelmanager/plugins/grass.py#L116). The position of parameters and also parameter names changed. Correct implementation would now be `self.rcfile = setup.init(self.gisdb, self.location, 'PERMANENT', self.gisbase)`.

Simple test:
```python
import os
import grass.script as grass
from grass.script import setup
rcfile = setup.init(os.environ['GISDBASE'], 'my_location', 'PERMANENT', os.environ['GISBASE'])
```

However, a fix would cause errors for users with GRASS version < 8. What could be done here?

**Comment by mwort** [comment]
Thanks for reporting this! Would a version check be enough to cater for both <8 and >8? E.g.:
from grass.script import core as gcore
```
if int(gcore.version()['version'].split('.')[0]) == 7:
    ...
else:
    ...
```

**Comment by tpilz** [comment]
This doesn't work as for `gcore.version()` to work `setup.init()` is required (it calls grass `g.version`).

An alternative would be

```python
import subprocess
cmd = subprocess.getoutput('grass -v')
int(cmd[10])
```

but this assumes that GRASS is callable via system command `grass` and that the version number is string number 11 (checked that for GRASS 8.0.0 and 7.8.6). You think this would be a working solution?

**Comment by tpilz** [comment]
... just saw that class `GrassSession` provides variable `grassbin` which can be used ...
